spring:
  datasource:
    url: jdbc:h2:file:./data/playerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true